#Simulation
FILENAME_R = './Test/Chicago_Apr_11_2016.csv'
SIMULATION_CYCLE = 3  #every 3 minutes
RIDER_ROW_START = 0
RIDER_ROW_END = 1

#Rider Para
WAITING = "waiting"
SERVING  = "serving"
FINISHED = "finished"
CANCEL = "cancel"

DETOUR_WEIGH = 0.05
DISCOUNT_1 = 0.96
DISCOUNT_2 = 0.93
DISCOUNT_3 = 0.9
DISCOUNT_4 = 0.87

#Driver Para
VEHICLE_CAPACITY = 4
IDLE = 'idle'
INSERVICE ='inservice'
COST_PER_MINUTE = 0.3*SIMULATION_CYCLE
SAT_PRICE = 1.5
SAT_TIME = 0.8


